# Change these first
owner: safe-global # Your GitHub organization or username, where this repository lives
repo: safe-services-status # The name of this repository
skipTopicsUpdate: true
sites:
  - name: Safe Client Gateway (Unified)
    url: https://safe-client.safe.global/health/ready/
  - name: Safe Tx Service (Mainnet)
    url: https://safe-transaction-mainnet.safe.global/check/
  - name: Safe Tx Service (Gnosis Chain)
    url: https://safe-transaction-gnosis-chain.safe.global/check/
  - name: Safe Tx Service (Goerli)
    url: https://safe-transaction-goerli.safe.global/check/
  - name: Safe Tx Service (Binance Smart Chain)
    url: https://safe-transaction-bsc.safe.global/check/
  - name: Safe Tx Service (Polygon - Matic)
    url: https://safe-transaction-polygon.safe.global/check/
  - name: Safe Tx Service (Base Testnet)
    url: https://safe-transaction-base-testnet.safe.global/check/
  - name: Safe Tx Service (Celo)
    url: https://safe-transaction-celo.safe.global/check/
  - name: Safe Tx Service (Arbitrum)
    url: https://safe-transaction-arbitrum.safe.global/check/
  - name: Safe Tx Service (Avalanche)
    url: https://safe-transaction-avalanche.safe.global/check/
  - name: Safe Tx Service (Optimism)
    url: https://safe-transaction-optimism.safe.global/check/
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.safe.global
  # baseUrl: /safe-services-status
  logoUrl: https://pbs.twimg.com/profile_images/1643941027898613760/gyhYEOCE_400x400.jpg
  name: Safe Ecosystem Foundation Backend Status
  introTitle: Status for the **Safe Ecosystem Foundation** Backend
  introMessage: Safe Ecosystem Foundation Backend Status
  favicon: https://app.safe.global/favicon.ico
  navbar:
    - title: Indexing Status
      href: https://safe-react-status.netlify.app/
    - title: Safe Infrastructure
      href: https://github.com/safe-global/safe-infrastructure
    - title: Help docs
      href: https://help.safe.global/en/
    - title: Dev docs
      href: https://docs.safe.global/
