# Change these first
owner: gnosis # Your GitHub organization or username, where this repository lives
repo: safe-services-status # The name of this repository

sites:
  - name: Unified Safe Client Gateway
    url: https://safe-client.gnosis.io/health/
  - name: Safe Transaction Service Mainnet
    url: https://safe-transaction.mainnet.gnosis.io/check/
  - name: Safe Transaction Service Rinkeby
    url: https://safe-transaction.rinkeby.gnosis.io/check/
  - name: Safe Transaction Service xDai
    url: https://safe-transaction.xdai.gnosis.io/check/
  - name: Safe Transaction Service Goerli
    url: https://safe-transaction.goerli.gnosis.io/check/
  - name: Safe Transaction Service Binance Smart Chain
    url: https://safe-transaction.bsc.gnosis.io/check/
  - name: Safe Transaction Service Polygon (Matic)
    url: https://safe-transaction.polygon.gnosis.io/check/
  - name: Safe Transaction Service EWC
    url: https://safe-transaction.ewc.gnosis.io/check/
  - name: Safe Transaction Service Volta
    url: https://safe-transaction.volta.gnosis.io/check/
  - name: Safe Transaction Service Arbitrum
    url: https://safe-transaction.arbitrum.gnosis.io/check/
